spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://tp2.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: itinnova
        password: Useradmin123
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.SQLServer2012Dialect
    mail:
        host: smtp.gmail.com
        username: leyva.calle1403@gmail.com
        password: zxfjbrchgptmsblb
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
